name: coffee_repository
description: A Dart Repository which manages the coffee domain.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.4.1 <4.0.0'

global_options:
  freezed:freezed:
    runs_before:
      - isar_generator:isar_generator

dependencies:
  json_annotation: ^4.9.0
  dartz: ^0.10.1
  http: ^1.2.1
  isar: 
    version: 3.1.7
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs: # contains Isar Core
    version: 3.1.7
    hosted: https://pub.isar-community.dev/

dev_dependencies:
  build_runner: ^2.4.10
  json_serializable: ^6.8.0
  test: ^1.16.4
  freezed: ^2.5.3
  freezed_annotation: ^2.4.1
  isar_generator: 
    version: 3.1.7
    hosted: https://pub.isar-community.dev/

dependency_overrides:
  meta: ^1.14.0
